server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: admin
    password: admin123

jwt:
  secret: b7f3c9a8e4d2f6b1c8a9e3f4d7b2c1e8a6d9f3b7c2e1a4d8f6b9c3e7a2d1f5c8
  expiration: 900000 # 15 minutos