server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres

jwt:
  secret: mySuperSecretKey123456
  expiration: 900000 # 15 minutos